# Generated by Django 5.1 on 2025-01-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('FastFoods', 'Fast Foods'), ('Snacks', 'Snacks/BreakFasts'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Desserts', 'Desserts')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='menu_images/')),
            ],
        ),
    ]
