# Generated by Django 5.1 on 2025-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_orderupdate_order_id_orderupdate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
