# Generated by Django 5.1 on 2025-01-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
