# Generated by Django 5.1 on 2025-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_order_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
