# Generated by Django 6.0.4 on 2026-04-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_order_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
